//
//  MockMeshBackend.swift
//  Eternal Lite — Offline Mesh Relay
//
//  PURPOSE: Simulates the server-side endpoint that receives OrderPackets
//  uploaded by any mesh node (originator or relay). The critical invariant
//  is idempotency-by-UUID: no matter how many devices upload the same
//  packet, exactly ONE order is created.
//
//  WHY IDEMPOTENCY IS ESSENTIAL FOR MESH:
//  ───────────────────────────────────────
//  In a mesh scenario, multiple relay nodes may each regain connectivity
//  at different times and all attempt to upload the same packet. Without
//  dedup, the restaurant would receive 3 copies of the same order.
//
//  The mechanism:
//    • Every OrderPacket has a UUID `id` generated by the originating device.
//    • The backend checks this ID against processedOrderIDs (Set<UUID>).
//    • If already present → returns .alreadyProcessed (idempotent success).
//    • If new → validates signature, creates the order, inserts the ID.
//
//  This is identical to how real payment processors handle idempotency keys
//  (Stripe uses the same pattern for their Idempotency-Key header).
//
//  PRODUCTION NOTE:
//  In production this would be a persistent store (PostgreSQL unique constraint
//  on order_id) not an in-memory Set, so it survives server restarts.
//

import Foundation

// MARK: - Backend Response Types

public enum BackendUploadResult {
    /// First time this packet was seen — order created successfully
    case created(confirmedOrderId: String)
    /// Packet was already processed by a prior upload — idempotent no-op
    case alreadyProcessed(confirmedOrderId: String)
    /// Packet rejected (invalid signature, missing COD flag, TTL exceeded, etc.)
    case rejected(reason: String)
    /// Transient server error — caller should retry
    case serverError(String)
}

// MARK: - MockMeshBackend

/// In-memory mock of the backend order endpoint.
/// Thread-safe via @MainActor — all callers in this app are already on MainActor.
@MainActor
public final class MockMeshBackend {

    public static let shared = MockMeshBackend()

    // MARK: - State

    /// The idempotency key store. In production: a DB unique index on order_id.
    /// Key: packet UUID → Value: server-assigned order confirmation ID
    private var processedOrderIDs: [UUID: String] = [:]

    /// All confirmed orders (for display/demo purposes)
    private(set) var confirmedOrders: [ConfirmedOrder] = []

    /// Simulated processing delay (realistic for a demo on Wi-Fi)
    public var simulatedLatencySeconds: Double = 0.8

    /// If true, the next upload call returns a transient serverError so we can
    /// demo the retry path in the debug overlay
    public var simulateNextCallFails: Bool = false

    private let signer = MeshPacketSigner.shared

    private init() {}

    // MARK: - Public API

    /// Submit an OrderPacket to the mock backend.
    ///
    /// This is the only entry point. MeshUploadService calls this whenever
    /// it detects connectivity and has a packet to submit.
    ///
    /// The method is async to model the real network round-trip.
    public func submit(packet: OrderPacket) async -> BackendUploadResult {

        // Simulate network latency
        try? await Task.sleep(for: .seconds(simulatedLatencySeconds))

        // ── Simulated transient failure (for demo) ──────────────────────
        if simulateNextCallFails {
            simulateNextCallFails = false
            return .serverError("Simulated 503 — retry in 5s")
        }

        // ── Idempotency check ───────────────────────────────────────────
        if let existingConfirmation = processedOrderIDs[packet.id] {
            #if DEBUG
            print("♻️  MockBackend: Duplicate upload for \(packet.id.uuidString.prefix(8))… → returning cached ack '\(existingConfirmation)'")
            #endif
            return .alreadyProcessed(confirmedOrderId: existingConfirmation)
        }

        // ── Validation ──────────────────────────────────────────────────

        // 1. Must be COD. The backend REJECTS any packet where codFlag == false.
        //    This enforces the deliberate design constraint: no payment data in
        //    the mesh. If someone crafts a packet with codFlag = false, it is
        //    rejected here before any order is created.
        guard packet.codFlag else {
            return .rejected(reason: "Non-COD orders cannot be submitted via mesh relay. Payment must be processed online.")
        }

        // 2. Hop count sanity check (belt-and-suspenders; relay layer already
        //    enforces this, but backend is the authoritative validator)
        guard packet.hopCount <= MeshConfig.maxHops else {
            return .rejected(reason: "Hop count \(packet.hopCount) exceeds maximum \(MeshConfig.maxHops)")
        }

        // 3. Packet freshness — reject orders older than 24 hours
        //    Prevents replaying a legitimate old packet after a long offline stint
        let ageSeconds = Date().timeIntervalSince(packet.timestamp)
        guard ageSeconds < 86400 else {
            return .rejected(reason: "Packet expired — timestamp is \(Int(ageSeconds / 3600))h old")
        }

        // 4. Signature verification — reject tampered packets
        do {
            try signer.verify(packet)
        } catch {
            return .rejected(reason: "Invalid signature: \(error.localizedDescription)")
        }

        // ── Create the order ────────────────────────────────────────────
        let confirmationId = "ORD-MESH-\(String(packet.id.uuidString.prefix(8)).uppercased())"
        let confirmed = ConfirmedOrder(
            confirmationId: confirmationId,
            packetId: packet.id,
            restaurantName: packet.restaurantName,
            items: packet.items,
            deliveryAddress: packet.deliveryAddress,
            receivedAt: Date(),
            uploadedVia: packet.hopCount == 0 ? .directUpload : .meshRelay(hops: packet.hopCount)
        )

        // Persist in the idempotency store (in-memory for hackathon)
        processedOrderIDs[packet.id] = confirmationId
        confirmedOrders.append(confirmed)

        #if DEBUG
        let via = packet.hopCount == 0 ? "direct" : "mesh relay (\(packet.hopCount) hop(s))"
        print("✅ MockBackend: Created order '\(confirmationId)' for '\(packet.restaurantName)' via \(via)")
        #endif

        return .created(confirmedOrderId: confirmationId)
    }

    // MARK: - Demo Helpers

    /// Returns the confirmation ID for a packet if it has already been processed
    public func confirmationId(for packetId: UUID) -> String? {
        processedOrderIDs[packetId]
    }

    /// How many unique orders have been confirmed (dedup count for debug overlay)
    public var confirmedOrderCount: Int { processedOrderIDs.count }

    /// Clear all state (demo reset)
    public func reset() {
        processedOrderIDs.removeAll()
        confirmedOrders.removeAll()
    }
}

// MARK: - ConfirmedOrder

/// A successfully created order as seen by the backend.
public struct ConfirmedOrder: Identifiable {
    public let id = UUID()
    public let confirmationId: String
    public let packetId: UUID
    public let restaurantName: String
    public let items: [PacketOrderItem]
    public let deliveryAddress: String
    public let receivedAt: Date
    public let uploadedVia: UploadPath

    public enum UploadPath {
        case directUpload
        case meshRelay(hops: Int)

        public var displayString: String {
            switch self {
            case .directUpload:         return "Direct upload"
            case .meshRelay(let hops):  return "Mesh relay (\(hops) hop\(hops == 1 ? "" : "s"))"
            }
        }
    }
}
